[package]
name    = "demo_ultralight"
version.workspace = true
edition.workspace = true

[dependencies]
imruski             = { workspace = true, features = ["ultralight"] }
imruski-ultralight  = { workspace = true }
log                 = { workspace = true }
env_logger          = "0.11"